version: 1.40.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
install:
- cmd: >-
    appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    ninja --version
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

    cd build

    cmake -G Ninja -DQt5_DIR=C:/Qt/5.9.1/msvc2015/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_63_0 -DCMAKE_BUILD_TYPE=Release -DLSLAPPS_LabRecorder=1 -DCMAKE_INSTALL_PREFIX=install ../

    cmake --build . --config Release --target LSLPACKAGE
artifacts:
- path: build/lslinstall
  name: lsl_Win32_$(APPVEYOR_BUILD_VERSION)_${APPVEYOR_REPO_COMMIT}
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: zcgGai0IfIlkwU5IXEvoJ/Kr+w2DbKIBJr/677Q52BPwUT0aFWSvJuZp2obpY3u5
  subject: tstenner
  repo: labstreaminglayer
  package: LSL
  publish: false
  explode: false
  override: false
